//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and cf-service-operator-cop contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CFServiceOperator) DeepCopyInto(out *CFServiceOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CFServiceOperator.
func (in *CFServiceOperator) DeepCopy() *CFServiceOperator {
	if in == nil {
		return nil
	}
	out := new(CFServiceOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CFServiceOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CFServiceOperatorList) DeepCopyInto(out *CFServiceOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CFServiceOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CFServiceOperatorList.
func (in *CFServiceOperatorList) DeepCopy() *CFServiceOperatorList {
	if in == nil {
		return nil
	}
	out := new(CFServiceOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CFServiceOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CFServiceOperatorSpec) DeepCopyInto(out *CFServiceOperatorSpec) {
	*out = *in
	out.Spec = in.Spec
	out.Image = in.Image
	in.KubernetesProperties.DeepCopyInto(&out.KubernetesProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CFServiceOperatorSpec.
func (in *CFServiceOperatorSpec) DeepCopy() *CFServiceOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(CFServiceOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CFServiceOperatorStatus) DeepCopyInto(out *CFServiceOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CFServiceOperatorStatus.
func (in *CFServiceOperatorStatus) DeepCopy() *CFServiceOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(CFServiceOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
